-- The schema as Hibernate created it (ddl-auto: update) before the switch to jOOQ, with Hibernate's
-- column order and constraint names, so new databases match the existing ones. Existing databases
-- are baselined at this version instead of running it (spring.flyway.baseline-on-migrate).
-- The SPRING_SESSION tables are created by Spring Session (spring.session.jdbc.initialize-schema).

create table app_users (
    id bigint generated by default as identity,
    created_at timestamp(6) with time zone not null,
    email varchar(255) not null,
    google_sub varchar(255) not null,
    last_login_at timestamp(6) with time zone,
    name varchar(255),
    role varchar(255) not null,
    constraint app_users_pkey primary key (id),
    constraint uk4vj92ux8a2eehds1mdvmks473 unique (email),
    constraint app_users_role_check check (role in ('ADMIN', 'USER'))
);

create table inventory_items (
    id bigint generated by default as identity,
    category varchar(255) not null,
    country varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    name varchar(255) not null,
    price double precision not null,
    quantity integer not null,
    vinmonopolet_code varchar(255) not null,
    constraint inventory_items_pkey primary key (id)
);

create table lotteries (
    id bigint generated by default as identity,
    created_at timestamp(6) with time zone not null,
    name varchar(255) not null,
    status varchar(255) not null,
    wine_count integer,
    constraint lotteries_pkey primary key (id),
    constraint lotteries_status_check check (status in ('OPEN', 'DRAWING', 'CLOSED'))
);

create table lottery_prizes (
    id bigint generated by default as identity,
    created_at timestamp(6) with time zone not null,
    position integer not null,
    lottery_id bigint not null,
    constraint lottery_prizes_pkey primary key (id),
    constraint uke15svj241njpoda24js4til0k unique (lottery_id, position),
    constraint fk3f6f0lv5bl6s7qktjua1nipqd foreign key (lottery_id) references lotteries (id)
);

create table participants (
    id bigint generated by default as identity,
    created_at timestamp(6) with time zone not null,
    name varchar(255) not null,
    photo_content_type varchar(255),
    photo_data bytea,
    tag varchar(255) not null,
    constraint participants_pkey primary key (id),
    constraint ukny4365q8au39xxeqwdfr0ax3q unique (tag)
);

create table prize_item_slots (
    id bigint generated by default as identity,
    quantity integer not null,
    inventory_item_id bigint not null,
    prize_id bigint not null,
    constraint prize_item_slots_pkey primary key (id),
    constraint fk6dg9o7kgk50p1v57hg0hso4a4 foreign key (prize_id) references lottery_prizes (id),
    constraint fkeexgj5j6y1c403qsvogdw4p1h foreign key (inventory_item_id) references inventory_items (id)
);

create table tickets (
    id bigint generated by default as identity,
    created_at timestamp(6) with time zone not null,
    ticket_number integer not null,
    won boolean not null,
    lottery_id bigint not null,
    participant_id bigint not null,
    constraint tickets_pkey primary key (id),
    constraint fk9c81njng8gradmnveaeho74vt foreign key (lottery_id) references lotteries (id),
    constraint fksdq766q038dmeacj3eo65h3kt foreign key (participant_id) references participants (id)
);

create table winners (
    id bigint generated by default as identity,
    drawn_at timestamp(6) with time zone not null,
    position integer not null,
    lottery_id bigint not null,
    participant_id bigint not null,
    prize_id bigint,
    ticket_id bigint not null,
    constraint winners_pkey primary key (id),
    constraint fkg3h1k0jyss35cs3nvyl9e65va foreign key (participant_id) references participants (id),
    constraint fkjqnuasjt7cpw1s7jqdvvpguqt foreign key (ticket_id) references tickets (id),
    constraint fkm2ngyephc7xqfrdaxjug1mvt7 foreign key (prize_id) references lottery_prizes (id),
    constraint fkoewmqew8ul9i7dx4pw0ur5t1g foreign key (lottery_id) references lotteries (id)
);

create table vg_products (
    product_id varchar(255) not null,
    cork_type varchar(255),
    country varchar(255),
    created_at timestamp(6) with time zone not null,
    discontinued boolean default false not null,
    grape varchar(255),
    main_product_type_name varchar(255),
    order_type varchar(255),
    origin varchar(255),
    packaging_material varchar(255),
    price double precision,
    product_group_name varchar(255),
    product_short_name varchar(255),
    product_type_name varchar(255),
    region_detailed varchar(255),
    sales_price_per_liter double precision,
    status_checked_at timestamp(6) with time zone,
    sub_product_type_name varchar(255),
    sub_region varchar(255),
    vmp_price double precision,
    vmp_vintage integer,
    volume double precision,
    volume_type varchar(255),
    constraint vg_products_pkey primary key (product_id)
);

create table vg_reviews (
    id bigint not null,
    alcohol_level double precision,
    article varchar(255),
    author_description text,
    barrel integer,
    bitterness integer,
    colour varchar(255),
    created_at timestamp(6) with time zone not null,
    freshness integer,
    fruit integer,
    fullness integer,
    grade integer not null,
    image_url varchar(500),
    lead varchar(255),
    odour varchar(255),
    price double precision,
    price_per_score double precision,
    reviewed_at timestamp(6) with time zone not null,
    sales_price_per_liter double precision,
    score integer not null,
    source_updated_at timestamp(6) with time zone not null,
    spice integer,
    sugar_content varchar(255),
    sweetness integer,
    tannins integer,
    taste varchar(255),
    vintage integer,
    product_id varchar(255) not null,
    constraint vg_reviews_pkey primary key (id),
    constraint fkj1kpr5ap2vbd8f92xy5vl99mv foreign key (product_id) references vg_products (product_id)
);

create table vmp_horten_products (
    product_id varchar(255) not null,
    alcohol double precision,
    country varchar(255),
    horten_stock integer,
    main_category varchar(255),
    main_category_code varchar(255),
    main_sub_category varchar(255),
    main_sub_category_code varchar(255),
    name varchar(255) not null,
    price double precision,
    product_selection varchar(255),
    stock_checked_at timestamp(6) with time zone not null,
    url varchar(255),
    vintage integer,
    volume double precision,
    constraint vmp_horten_products_pkey primary key (product_id)
);
